jenkinsci/gitea-plugin

src/main/java/org/jenkinsci/plugin/gitea/GiteaSCMNavigator.java
src/main/java/org/jenkinsci/plugin/gitea/GiteaSCMSource.java
src/main/java/org/jenkinsci/plugin/gitea/client/api/GiteaConnection.java
src/main/java/org/jenkinsci/plugin/gitea/client/impl/DefaultGiteaConnection.java
src/test/java/org/jenkinsci/plugin/gitea/client/mock/MockGiteaConnection.java

This PR fixes the [issue](https://issues.jenkins-ci.org/browse/JENKINS-52112) about fetching organizational repositories for me.
This way the user doesn't have to be an administrator.

Allow fetching organizational repositories

---

src/main/java/org/jenkinsci/plugin/gitea/GiteaSCMNavigator.java

When using organization folder, the website link was logged even when none was configured.

Fixed org website display when none specified

---

src/main/java/org/jenkinsci/plugin/gitea/GiteaSCMBuilder.java

As specified in documentation:
https://docs.oracle.com/javase/7/docs/api/java/net/URI.html#getPort()
getPort() returns "The port component of this URI, or -1 if the port is undefined"
I have added the condition for -1 so the uri doesn't end up with the port -1.

[FIXED JENKINS-61996] Check for not specified port in SSH URI

---

.gitignore
src/main/java/org/jenkinsci/plugin/gitea/ExcludeArchivedRepositoriesTrait.java
src/main/java/org/jenkinsci/plugin/gitea/GiteaSCMNavigator.java
src/main/java/org/jenkinsci/plugin/gitea/GiteaSCMNavigatorContext.java
src/main/java/org/jenkinsci/plugin/gitea/client/api/GiteaRepository.java
src/main/resources/org/jenkinsci/plugin/gitea/ExcludeArchivedTrait/config.jelly
src/main/resources/org/jenkinsci/plugin/gitea/GiteaSCMNavigator/help.html
src/main/resources/org/jenkinsci/plugin/gitea/Messages.properties
src/test/java/org/jenkinsci/plugin/gitea/client/impl/DefaultGiteaConnectionTest.java
src/test/java/org/jenkinsci/plugin/gitea/client/impl/DefaultGiteaConnection_PagedRequests_Test.java

This is required by me and inspired by jenkinsci/github-branch-source-plugin#274
fixes [JENKINS-64353](https://issues.jenkins.io/browse/JENKINS-64353)

feat: add archived filter (JENKINS-64353)

---

src/main/java/org/jenkinsci/plugin/gitea/GiteaSCMSource.java
src/main/java/org/jenkinsci/plugin/gitea/client/api/GiteaVersion.java

Based on https://github.com/go-gitea/gitea/pull/9995, fix https://issues.jenkins-ci.org/browse/JENKINS-60017

FIX JENKINS-60017

---

pom.xml
src/main/java/org/jenkinsci/plugin/gitea/GiteaSCMBuilder.java

- Bump Jenkins version according to [Recommended Jenkins minimum version](https://www.jenkins.io/doc/developer/plugin-development/choosing-jenkins-baseline/)
- Fix build error regarding entropy class
- Configure build properties

Dependency updates

---

src/main/java/org/jenkinsci/plugin/gitea/ForkPullRequestDiscoveryTrait.java
src/main/java/org/jenkinsci/plugin/gitea/GiteaSCMNavigator.java
src/main/java/org/jenkinsci/plugin/gitea/OriginPullRequestDiscoveryTrait.java
src/main/java/org/jenkinsci/plugin/gitea/SSHCheckoutTrait.java
src/main/java/org/jenkinsci/plugin/gitea/TagDiscoveryTrait.java
src/main/java/org/jenkinsci/plugin/gitea/WebhookRegistrationTrait.java

Hi 
First of all, a big thanks for picking up maintenance for this plugin again!
We are using this plugin with an initial root job using the job DSL. The current version of the plugin has two problems regarding DSL support:
- it is impossible to configure the `traits` of `giteaSCMNavigator`
- it is impossible to configure the `giteaForkDiscovery` trait
This PR adds full support for configuration via the Job DSL plugin.
Fixes:
- https://issues.jenkins.io/browse/JENKINS-66584
- https://issues.jenkins.io/browse/JENKINS-64580

Make plugin compatible with Job DSL

---

.github/release-drafter.yml
.github/workflows/cd.yaml
.mvn/maven.config
pom.xml

To reduce manual overhead on releases, this can be automated.

Enable cd workflow

---

.github/workflows/cd.yaml
README.md
pom.xml

The last Pull Request broke the incremental builds whilst trying to fix the release tagging/deploy syntax.
The used workflow to deploy the artifact and create a tag + release on GitHub does not support a clean version such as `1.4.0` instead of `1.4.0-rc....`. This is due to the hardcoded `-Dset.changelist` flag which does not allow skipping the suffix.
As the Gitea plugin should have clean release names, I switched to my fork where this feature is implemented. We can use it as long as the [upstream PR for that workflow](https://github.com/jenkins-infra/jenkins-maven-cd-action/pull/13) is not merged.
In addition to that, I've came to the conclusion that it wouldn't be wise to not skip all the interim versions between 1.4.0 and 1.5.0. Why should we do this. So back to 1.4.1. 😄
We now have …

Fix release versioning + incremental builds

---

src/main/java/org/jenkinsci/plugin/gitea/client/impl/DefaultGiteaConnection.java

As a result of PR #29 it happens that some users cannot fetch branches
with slashes in their names anymore.
Looks like it's an issue with manually triggering jobs.
Regression from: [JENKINS-65796](https://issues.jenkins.io/browse/JENKINS-65796)
Fixes: [JENKINS-67068](https://issues.jenkins.io/browse/JENKINS-67068)

[JENKINS-67068] Fix regression for branch names with slashes

---

src/main/java/org/jenkinsci/plugin/gitea/credentials/PersonalAccessTokenImpl.java

Right now, one has to use `personalAccessTokenImpl` to define a Jenkins
credential for Gitea token.
This adds the Symbol `giteaAccessToken` so that it is possible to
identify their relation with the Gitea plugin in Configuration as Code
snippets.
It is still possible to use the old one.
```diff
credentials:
system:
domainCredentials:
- credentials:
-      - personalAccessTokenImpl:
+      - giteaAccessToken:
id: gitea-token
scope: GLOBAL
token: "personal-gitea-token-placeholder"
```

Provide dedicated symbol for personal access token

---

.github/workflows/cd.yaml

The recent release 1.4.1 showed that pushing to the default branch within a GitHub workflow is not possible with our current branch protection. As an alternative way to automate the version bump, a PR is created which won't show up in future releases (due to its label).

Switch to PR creation for version bump

---

src/main/java/org/jenkinsci/plugin/gitea/GiteaSCMBuilder.java

Also resolves important TODO. I couldn't find any failing `git clone` without this code.

Remove useless code for building clone url

---

docs/README.md

The info section **This is only necessary when using `branch-api` plugin version >=2.7.0** breaks formatting of the main plugin description online. (https://plugins.jenkins.io/gitea/)

separate the last info section

---

Jenkinsfile

This PR removes the deprecated `recommendedConfigurations` syntax to favor a proper configuration.
Internally, `recommendedConfigurations` does no longer apply any configuration it used to apply years ago.
I'll expedite the merge, once the infrastructure changes to ci.jenkins.io have been merged into production, to prevent failing builds on the default branch and new pull requests.

Replace deprecated 'recommendedConfigurations' with replacement

---

src/main/java/org/jenkinsci/plugin/gitea/GiteaSCMFileSystem.java

Jenkins token permissions potentially invalid to access source repo.
This is the cause of issue [JENKINS-69719](https://issues.jenkins.io/browse/JENKINS-69719).
All required Gitea Pull Request data can be accessed via target repo.
Replace access to potentially inaccessible source repository by references in target repository Pull Request head.
The change affects token/credential permission scope on the Gitea server.
With the changed source for data access, the `MultiBranchPipeline` scan completes.
Jenkins can pull/checkout (moving) head of pull request.
Resolution to commit hash is done independently in body of `GiteaSCMFileSystem` constructor.
```[tasklist]
```

Fix JENKINS-69719: Fetch PR data from target repo

---

.vscode/settings.json
pom.xml
src/main/java/org/jenkinsci/plugin/gitea/GiteaNotifier.java
src/main/java/org/jenkinsci/plugin/gitea/GiteaReleaseNotifier.java
src/main/java/org/jenkinsci/plugin/gitea/GiteaReleaseSCMEvent.java
src/main/java/org/jenkinsci/plugin/gitea/GiteaSCMBuilder.java
src/main/java/org/jenkinsci/plugin/gitea/GiteaSCMFileSystem.java
src/main/java/org/jenkinsci/plugin/gitea/GiteaSCMNavigator.java
src/main/java/org/jenkinsci/plugin/gitea/GiteaSCMSource.java
src/main/java/org/jenkinsci/plugin/gitea/GiteaSCMSourceContext.java
src/main/java/org/jenkinsci/plugin/gitea/GiteaSCMSourceRequest.java
src/main/java/org/jenkinsci/plugin/gitea/ReleaseDiscoveryTrait.java
src/main/java/org/jenkinsci/plugin/gitea/ReleaseSCMHead.java
src/main/java/org/jenkinsci/plugin/gitea/ReleaseSCMHeadCategory.java
src/main/java/org/jenkinsci/plugin/gitea/ReleaseSCMRevision.java
src/main/java/org/jenkinsci/plugin/gitea/client/api/GiteaConnection.java
src/main/java/org/jenkinsci/plugin/gitea/client/api/GiteaRelease.java
src/main/java/org/jenkinsci/plugin/gitea/client/api/GiteaReleaseEvent.java
src/main/java/org/jenkinsci/plugin/gitea/client/api/GiteaReleaseEventType.java
src/main/java/org/jenkinsci/plugin/gitea/client/impl/DefaultGiteaConnection.java
src/main/java/org/jenkinsci/plugin/gitea/tasks/GiteaAssetPublisher.java
src/main/resources/org/jenkinsci/plugin/gitea/Messages.properties
src/main/resources/org/jenkinsci/plugin/gitea/ReleaseDiscoveryTrait/config.jelly
src/main/resources/org/jenkinsci/plugin/gitea/ReleaseDiscoveryTrait/help-artifactToAssetMappingEnabled.html
src/main/resources/org/jenkinsci/plugin/gitea/ReleaseDiscoveryTrait/help-includeDrafts.html
src/main/resources/org/jenkinsci/plugin/gitea/ReleaseDiscoveryTrait/help-includePreReleases.html
src/main/resources/org/jenkinsci/plugin/gitea/ReleaseDiscoveryTrait/help.html
src/main/resources/org/jenkinsci/plugin/gitea/tasks/GiteaAssetPublisher/config.jelly
src/test/java/org/jenkinsci/plugin/gitea/client/mock/MockGiteaConnection.java

This PR adds the ability to discover releases in gitea as "branches" to be build seperatly.
It also adds an task for pipelines ("publishGiteaAssets") which works a little like copyArtifacts but uploads artifacts as an asset to the current building release.
The PR also contains an (toggleable) feature to "map" artifacts originally created via copyArtifacts to gitea release assets.
Relevant issues:
- [JENKINS-67790 - Upload built artifacts](https://issues.jenkins.io/browse/JENKINS-67790)
___

Add gitea release handling

---

.github/dependabot.yml
.github/workflows/cd.yaml
.mvn/maven.config
pom.xml

Most of the plugins I use fully migrated to JEP-229[^1]. It seems stable enough and reduces manual overhead when releasing the plugin.
After quick chat with @lafriks in Discord, we decided to fully enable automated releases. The first part happened in #35. I followed the official docs[^2]. This will eliminate the version bump PR after each release.
This will change the versioning pattern to `<amount-of-commits-on-main-branch>.v<HEAD>`. When the next release is crafted, we should add a note to the release about this version change.
I also configured Dependabot to get monthly updates for our dependencies.
[^1]: https://github.com/jenkinsci/jep/blob/master/jep/229/README.adoc
[^2]: https://www.jenkins.io/doc/developer/publishing/releasing-cd/

Fully enable automated releases

---

README.md

And update java version in docs :D
The `documentation` label should be enough to trigger a release, once merged.

Update gitea.io to gitea.com

---

src/main/java/org/jenkinsci/plugin/gitea/GiteaNotifier.java
src/main/java/org/jenkinsci/plugin/gitea/client/api/GiteaCommitState.java

Jenkins job that have Result `NOT_BUILT` are reported as errors which confuses developers.
Context for `NOT_BUILT`: https://github.com/jenkinsci/workflow-job-plugin/pull/200

Handle NOT_BUILT results more clearly

---

pom.xml

I am trying to add the `gitea` plugin to the plugin BOM. In order to do that, we need to modify the `scm.connection` to start with `scm:git:https` instead of just `https`.
Reference: https://www.jenkins.io/doc/developer/tutorial-improve/update-scm-url/
`mvn clean verify`

Use https: for scm URL

---

src/main/java/org/jenkinsci/plugin/gitea/GiteaBrowser.java
src/main/java/org/jenkinsci/plugin/gitea/GiteaLink.java
src/main/java/org/jenkinsci/plugin/gitea/GiteaWebhookAction.java
src/main/java/org/jenkinsci/plugin/gitea/servers/GiteaServers.java
src/main/java/org/jenkinsci/plugin/gitea/tasks/GiteaAssetPublisher.java

Migrate from deprecated EE 8 functionality to non-deprecated EE 9 equivalents.
`mvn clean verify`

Migrate from EE 8 to EE 9
